### ISSUE TITLE
add self-hosted docker setup

### ISSUE THREAD

**Issue by prateeksachan** [bolna-ai/bolna#17]

**Comment by paulocr** [comment]
FYI I needed to add gcc and g++ to ```bolna_server.Dockerfile``` for the local setup to work otherwise some python packages would not compile (i.e. libstemmer), not sure if it's something that needs to be changed.

```
RUN apt-get update && apt-get install -y --no-install-recommends \
  libgomp1 \
  git \
  ffmpeg \
  gcc \
  g++
```

**Comment by prateeksachan** [comment]
hey @paulocr thanks for reporting it. Will check and update you.

**Comment by ydidwania** [comment]
Faced the same thing

**Comment by AlexM4H** [comment]
> FYI I needed to add gcc and g++ to `bolna_server.Dockerfile` for the local setup to work otherwise some python packages would not compile (i.e. libstemmer), not sure if it's something that needs to be changed.
> 
> ```
> RUN apt-get update && apt-get install -y --no-install-recommends \
>   libgomp1 \
>   git \
>   ffmpeg \
>   gcc \
>   g++
> ```

Helps me 1+

**Comment by prateeksachan** [comment]
@paulocr , @AlexM4H this is now fixed as part of https://github.com/bolna-ai/bolna/pull/33/commits/9176f1488d288074524999f61865e345054d2ac8. Thanks for highlighting it.
