### ISSUE TITLE
Documentation mismatch and unclear repository intention

### ISSUE THREAD

**Issue by AlexM4H** [bolna-ai/bolna#31]
Hi,

I find the project very exciting and am very interested in the functionality behind it. Unfortunately, this does not match the functions described in the documentation. I hope I am wrong about this. There seem to be significantly fewer API functions.

My questions:

What is the intention behind this repository?
Will the missing functions still be released?

The license of the project was recently changed. Can it please be explained why this was necessary? What was wrong with the AGPL license?

Thank you in advance for your reply and information! I am very curious about your explanations and hope for a lively further development of this project.

**Comment by AlexM4H** [comment]
Thank you for updating the README file.

**Comment by prateeksachan** [comment]
@AlexM4H have updated the REAME. Hopefully, it should be clearer now (or atleast relatively clearer). Please let me know if there's any more ambiguity. Happy to address them. Kindly close this if appropriate.

**Comment by AlexM4H** [comment]
What about the license change?

**Comment by prateeksachan** [comment]
what license change? it's MIT Licensed.

**Comment by AlexM4H** [comment]
Up to version 0.7.8 the GAPL V3 license was used.

**Comment by prateeksachan** [comment]
yes, but we changed it to MIT license.
