### ISSUE TITLE
Ambient audio tracks, (any specific file or folder with the audio files?)

### ISSUE THREAD

**Issue by abdulrahmanmajid** [bolna-ai/bolna#41]
Hi can someone help me with this 

 },
                "task_config": {
                    "ambient_noise_track": "office-ambience",
                    "hangup_after_LLMCall": false,
                    "hangup_after_silence": 10.0,
                    "ambient_noise": false,
                    "interruption_backoff_period": 0.0,
                    "backchanneling": false,
                    "backchanneling_start_delay": 5.0,
                    "optimize_latency": true,
                    "incremental_delay": 100.0,
                    "call_cancellation_prompt": null,
                    "number_of_words_for_interruption": 3.0,
                    "backchanneling_message_gap": 5.0,
                    "use_fillers": false

The ambient sound has a track

I wanna know where is that track coming from? Do we need to add our own audio file to some folder or is it using some cdn in some other file?

**Comment by prateeksachan** [comment]
thanks for reporting this @abdulrahmanmajid . have merged the missing files now.
