### ISSUE TITLE
Azure tts not sending any audio back to the user.

### ISSUE THREAD

**Issue by abdulrahmanmajid** [bolna-ai/bolna#50]
bolna-app-1   | 2024-10-18 11:54:00.341 INFO {task_manager} [_synthesize] ##### sending text to azuretts for generation: How are you doing Bruce?                                                                                           
bolna-app-1   | 2024-10-18 11:54:00.342 INFO {azure_synthesizer} [push] Pushed message to internal queue {'data': 'How are you doing Bruce?', 'meta_info': {'io': 'twilio', 'message_category': 'agent_welcome_message', 'stream_sid': 'MZc69b2ea4bd6875c12ad52ce72ef29c25', 'request_id': '34505986-423d-46fa-bbd6-60a826e4b461', 'cached': False, 'sequence_id': -1, 'format': 'pcm', 'text': 'How are you doing Bruce?', 'is_md5_hash': False, 'llm_generated': False, 'type': 'audio', 'synthesizer_start_time': 1729252440.3414614}}
bolna-app-1   | 2024-10-18 11:54:00.350 INFO {azure_synthesizer} [generate] Generating TTS response for message: {'data': 'How are you doing Bruce?', 'meta_info': {'io': 'twilio', 'message_category': 'agent_welcome_message', 'stream_sid': 'MZc69b2ea4bd6875c12ad52ce72ef29c25', 'request_id': '34505986-423d-46fa-bbd6-60a826e4b461', 'cached': False, 'sequence_id': -1, 'format': 'pcm', 'text': 'How are you doing Bruce?', 'is_md5_hash': False, 'llm_generated': False, 'type': 'audio', 'synthesizer_start_time': 1729252440.3414614}}
bolna-app-1   | 2024-10-18 11:54:00.350 INFO {azure_synthesizer} [generate] Caching is on
bolna-app-1   | 2024-10-18 11:54:00.350 INFO {inmemory_scalar_cache} [get] Cache miss for key How are you doing Bruce?
bolna-app-1   | 2024-10-18 11:54:00.350 INFO {azure_synthesizer} [generate] Not a cache hit []                        
bolna-app-1   | 2024-10-18 11:54:01.109 ERROR {azure_synthesizer} [__generate_http] Speech synthesis failed: ResultReason.Canceled
bolna-app-1   | Traceback (most recent call last):
bolna-app-1   |   File "/usr/local/lib/python3.10/site-packages/bolna/agent_manager/task_manager.py", line 1465, in __listen_synthesizer                                                                                                    
bolna-app-1   |     async for message in self.tools["synthesizer"].generate():
bolna-app-1   |   File "/usr/local/lib/python3.10/site-packages/bolna/synthesizer/azure_synthesizer.py", line 92, in generate                                                                                                               
bolna-app-1   |     message = wav_bytes_to_pcm(message)
bolna-app-1   |   File "/usr/local/lib/python3.10/site-packages/bolna/helpers/utils.py", line 93, in wav_bytes_to_pcm
bolna-app-1   |     rate, data = wavfile.read(wav_buffer)                                                             
bolna-app-1   |   File "/usr/local/lib/python3.10/site-packages/scipy/io/wavfile.py", line 650, in read
bolna-app-1   |     file_size, is_big_endian = _read_riff_chunk(fid)                                                  
bolna-app-1   |   File "/usr/local/lib/python3.10/site-packages/scipy/io/wavfile.py", line 521, in _read_riff_chunk   
bolna-app-1   |     raise ValueError(f"File format {repr(str1)} not understood. Only "
bolna-app-1   | ValueError: File format b'' not understood. Only 'RIFF' and 'RIFX' supported.                         
bolna-app-1   | 2024-10-18 11:54:01.112 ERROR {task_manager} [__listen_synthesizer] Error in synthesizer File format b'' not understood. Only 'RIFF' and 'RIFX' supported.                                                                  
bolna-app-1   | 2024-10-18 11:54:01.112 WARNING {runners} [run] Executing <Task finished name='Task-55' coro=<TaskManager.__listen_synthesizer() done, defined at /usr/local/lib/python3.10/site-packages/bolna/agent_manager/task_manager.py:1457> result=None created at /usr/local/lib/python3.10/asyncio/tasks.py:337> took 0.763 seconds
bolna-app-1   | 2024-10-18 11:54:01.295 INFO {deepgram_transcriber} [receiver] Connecton start time 1729252439.8952308 7 and 0.2

this is the payload used. 

{
    "agent_config": {
        "agent_name": "Alfred",
        "agent_type": "other",
        "agent_welcome_message": "How are you doing Bruce?",
        "tasks": [
            {
                "task_type": "conversation",
                "toolchain": {
                    "execution": "parallel",
                    "pipelines": [
                        [
                            "transcriber",
                            "llm",
                            "synthesizer"
                        ]
                    ]
                },
                "tools_config": {
                    "input": {
                        "format": "pcm",
                        "provider": "twilio"
                    },
                    "llm_agent": {
                        "agent_type": "simple_llm_agent",
                        "agent_flow_type": "streaming",
                        "routes": null,
                        "llm_config": {
                            "agent_flow_type": "streaming",
                            "provider": "openai",
                            "request_json": true,
                            "model": "gpt-4o-mini"
                        }
                    },
                    "output": {
                        "format": "pcm",
                        "provider": "twilio"
                    },
                    "synthesizer": {
                        "provider": "azuretts",
                        "provider_config": {
                            "voice": "en-US-AdamMultilingualNeural",
                            "model": "en-US-AdamMultilingualNeural",
                            "language":"en_US",
                            "sampling_rate": "24000"
                        },
                        "stream": true,
                        "buffer_size": 200,
                        "audio_format": "wav"
                    },
                    "transcriber": {
                        "encoding": "linear16",
                        "language": "en",
                        "provider": "deepgram",
                        "stream": true
                    }
                },
                "task_config": {
                    "hangup_after_silence": 30.0
                }
            }
        ]
    },
    "agent_prompts": {
        "task_1": {
            "system_prompt": "you are an ai voice agent."
        }
    },
    "account_id": "9a1879c1-6e38-47aa-b287-d71fb228ab49"
}

**Comment by akshaym1shra** [comment]
Is it fixed? I tried it today and am facing the same issue

**Comment by abdulrahmanmajid** [comment]
@akshaym1shra 

Hi, Yea I fixed this by a few changes in the payload I sent the solution on discord but ill share it here as well 


The main issue was with how the TTS configuration was being concatenated. The code was producing something like this:


"synthesizer": {
    "provider": "azuretts",
    "provider_config": {
        "voice": "en-US-AdamMultilingualNeural",
        "language": "en-US",
        "model": "neural"
    }
}
The response would end up as:

en_US-en-US-AdamMultilingualNeuralnural

This was causing the problem.

The second issue was in the code snippet:


def init(self, voice, language, model="neural", stream=False, sampling_rate=16000, buffer_size=400, caching=True, **kwargs):

The "n" in "neural" should actually be a capital "N."

Here’s what the correct configuration should look like:

"synthesizer": {
    "provider": "azuretts",
    "provider_config": {
        "voice": "AdamMultilingual",
        "language": "en-US",
        "model": "Neural"
    }
}

the response for this would be 

"en-US-AdamMultilingualNeural"
which matches the voice id from azure. 



along with changing the input and output twilio format from pcm to wav for azure.


"input": {
                        "format": "wav",
                        "provider": "twilio"



Hopefully, this helps anyone facing similar issues!
